# Main mapping: symbol → id CoinGecko
asset_map:
  BTC: bitcoin
  ETH: ethereum
  USDT: tether
  BNB: binancecoin
  ADA: cardano
  SOL: solana
  ETC: ethereum-classic
  USDC: usd-coin
  DOT: polkadot
  EGLD: elrond-erd-2
  GRT: the-graph
  ETHW: ethereum-pow-iou
  ENA: ethena
  SWAP: hyperswap
  HYPE: hyperliquid
  USD₮0: usdt0
  USDHL: hyper-usd